apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: django-web
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: adriangameromedina/centro-comercial:latest
        name: result
        ports:
        - containerPort: 8000
          name: result